CREATE EXTENSION postgis;

create table cidade (
    est_id bigint,
    id bigint generated by default as identity,
    cid_nome varchar(50),
    primary key (id)
);

create table estado (
    id bigint generated by default as identity,
    est_nome varchar(60),
    primary key (id)
);

create table fazenda (
    faz_area float4,
    faz_prod_anual float4,
    cid_id bigint,
    id bigint generated by default as identity,
    faz_nome varchar(60),
    faz_tipo_solo varchar(100),
    primary key (id)
);

create table relatorio (
    percentual_diff float4,
    rel_status smallint check (rel_status between 0 and 3),
    end_review timestamp(6),
    id bigint generated by default as identity,
    start_review timestamp(6),
    use_id bigint,
    primary key (id)
);

create table resultado (
    rel_sourch smallint check (rel_sourch between 0 and 1),
    created_at timestamp(6),
    id bigint generated by default as identity,
    rel_id bigint,
    tal_id bigint,
    rel_geom geometry,
    primary key (id)
);

create table talhao (
    tal_area float4,
    faz_id bigint,
    id bigint generated by default as identity,
    tal_cultura varchar(60),
    tal_nome varchar(60),
    tal_geom geometry,
    primary key (id)
);

create table usuario (
    use_role smallint check (use_role between 0 and 2),
    created_at timestamp(6),
    id bigint generated by default as identity,
    use_email varchar(100),
    use_nome varchar(60),
    primary key (id)
);

alter table if exists cidade 
    add constraint FK3jrphg3ll698ta68xi074uesj 
    foreign key (est_id) 
    references estado;

alter table if exists fazenda 
    add constraint FK1hovweo0237sowrvbo7vxvhkb 
    foreign key (cid_id) 
    references cidade;

alter table if exists relatorio 
    add constraint FK311ms1ya93wcjxc310qa3bv46 
    foreign key (use_id) 
    references usuario;

alter table if exists resultado 
    add constraint FKscn6k69cm3iw46msw9q3mx471 
    foreign key (rel_id) 
    references resultado;

alter table if exists resultado 
    add constraint FKg9vmapx1koo03j6n8ew5dj4u3 
    foreign key (tal_id) 
    references talhao;

alter table if exists talhao 
    add constraint FKnefek7ox53jp06g3bkkhyelkf 
    foreign key (faz_id) 
    references fazenda;

INSERT INTO estado (est_nome) VALUES ('Acre');
INSERT INTO estado (est_nome) VALUES ('Alagoas');
INSERT INTO estado (est_nome) VALUES ('Amapá');
INSERT INTO estado (est_nome) VALUES ('Amazonas');
INSERT INTO estado (est_nome) VALUES ('Bahia');
INSERT INTO estado (est_nome) VALUES ('Ceará');
INSERT INTO estado (est_nome) VALUES ('Distrito Federal');
INSERT INTO estado (est_nome) VALUES ('Espírito Santo');
INSERT INTO estado (est_nome) VALUES ('Goiás');
INSERT INTO estado (est_nome) VALUES ('Maranhão');
INSERT INTO estado (est_nome) VALUES ('Mato Grosso');
INSERT INTO estado (est_nome) VALUES ('Mato Grosso do Sul');
INSERT INTO estado (est_nome) VALUES ('Minas Gerais');
INSERT INTO estado (est_nome) VALUES ('Pará');
INSERT INTO estado (est_nome) VALUES ('Paraíba');
INSERT INTO estado (est_nome) VALUES ('Paraná');
INSERT INTO estado (est_nome) VALUES ('Pernambuco');
INSERT INTO estado (est_nome) VALUES ('Piauí');
INSERT INTO estado (est_nome) VALUES ('Rio de Janeiro');
INSERT INTO estado (est_nome) VALUES ('Rio Grande do Norte');
INSERT INTO estado (est_nome) VALUES ('Rio Grande do Sul');
INSERT INTO estado (est_nome) VALUES ('Rondônia');
INSERT INTO estado (est_nome) VALUES ('Roraima');
INSERT INTO estado (est_nome) VALUES ('Santa Catarina');
INSERT INTO estado (est_nome) VALUES ('São Paulo');
INSERT INTO estado (est_nome) VALUES ('Sergipe');
INSERT INTO estado (est_nome) VALUES ('Tocantins');