name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Checkstyle on main sources
        run: ./gradlew checkstyleMain

      - name: Run Checkstyle on test sources
        run: ./gradlew checkstyleTest

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Build
        run: ./gradlew bootJar

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run tests
        run: ./gradlew test